"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable no-console */
// Generator: computes per-serving nutrition (default selection) for every authored
// recipe via the engine and emits a baked, fully-typed Recipe[] catalog. Run it
// whenever the authored source or the ingredient dictionary changes.
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const recipeNutrition_1 = require("@/lib/recipeNutrition");
const recipeSource_1 = require("./recipeSource");
const AUTHORED = [
    ...recipeSource_1.AUTHORED_BREAKFASTS,
    ...recipeSource_1.AUTHORED_SALADS,
    ...recipeSource_1.AUTHORED_SOUPS,
    ...recipeSource_1.AUTHORED_MAINS,
    ...recipeSource_1.AUTHORED_SIDES,
    ...recipeSource_1.AUTHORED_DESSERTS,
    ...recipeSource_1.AUTHORED_SNACKS,
    ...recipeSource_1.AUTHORED_KIDS,
];
const projectRoot = path.resolve(__dirname, '..', '..');
let photoMap = {};
try {
    photoMap = JSON.parse(fs.readFileSync(path.join(projectRoot, 'src', 'lib', 'generated', 'recipePhotos.json'), 'utf8'));
}
catch {
    photoMap = {};
}
const recipes = [];
let allVerified = true;
let withPhoto = 0;
for (const authored of AUTHORED) {
    const result = (0, recipeNutrition_1.computeRecipeNutritionForSelection)(authored, undefined);
    if (result.confidence !== 'verified') {
        allVerified = false;
        console.error('NOT VERIFIED: ' + authored.id);
        for (const d of result.diagnostics) {
            if (d.via !== 'foodRef' || d.grams == null)
                console.error('  ' + d.name + ' [' + d.via + ', ' + ((_a = d.grams) !== null && _a !== void 0 ? _a : 'no grams') + ']');
        }
    }
    const photo = photoMap[authored.id];
    if (photo)
        withPhoto++;
    recipes.push({
        ...authored,
        nutritionPerServing: result.nutrition,
        nutritionConfidence: result.confidence,
        ...(photo ? { photoUri: photo.photoUri, photoCredit: { name: photo.name, url: photo.url, source: photo.source } } : {}),
    });
    const n = result.nutrition;
    console.log(authored.id.padEnd(30) + String(n.calories).padStart(5) + ' kcal  ' + result.confidence + (photo ? '  📷' : ''));
}
if (!allVerified) {
    console.error('\nAborting: some recipes are not verified.');
    process.exit(1);
}
const header = '// AUTO-GENERATED by scripts/generateRecipes.ts — do not edit by hand.\n' +
    '// Nutrition is computed deterministically from ingredient grams + foodRef.\n' +
    "import { Recipe } from '@/types/app';\n\n" +
    'export const VERIFIED_RECIPE_LIBRARY: Recipe[] = ';
const body = JSON.stringify(recipes, null, 2);
const output = header + body + ';\n';
const outPath = path.join(projectRoot, 'src', 'lib', 'generated', 'verifiedRecipeCatalog.ts');
fs.writeFileSync(outPath, output, 'utf8');
console.log('\nWrote ' + recipes.length + ' recipes -> ' + path.relative(projectRoot, outPath));
