/* eslint-disable no-console */
// Emits src/lib/generated/recipeImageMap.ts — a static require() map of the AI
// recipe photos in assets/recipes/. Static requires are Metro-friendly and load
// lazily per card. Run after generateAiPhotos.ts.
import * as fs from 'fs';
import * as path from 'path';

const projectRoot = path.resolve(__dirname, '..', '..');
const imgDir = path.join(projectRoot, 'assets', 'recipes');
const files = fs
  .readdirSync(imgDir)
  .filter((f) => f.endsWith('.jpg') && fs.statSync(path.join(imgDir, f)).size > 5000)
  .sort();

const entries = files
  .map((f) => {
    const id = f.replace(/\.jpg$/, '');
    return `  '${id}': require('../../../assets/recipes/${f}'),`;
  })
  .join('\n');

const out =
  '// AUTO-GENERATED by scripts/generateImageMap.ts — do not edit by hand.\n' +
  "import type { ImageSourcePropType } from 'react-native';\n\n" +
  'export const RECIPE_IMAGES: Record<string, ImageSourcePropType> = {\n' +
  entries +
  '\n};\n';

const outPath = path.join(projectRoot, 'src', 'lib', 'generated', 'recipeImageMap.ts');
fs.writeFileSync(outPath, out, 'utf8');
console.log('Wrote ' + files.length + ' image entries -> ' + path.relative(projectRoot, outPath));
