/* eslint-disable no-console */
// Generator: computes per-serving nutrition (default selection) for every authored
// recipe via the engine and emits a baked, fully-typed Recipe[] catalog. Run it
// whenever the authored source or the ingredient dictionary changes.
import * as fs from 'fs';
import * as path from 'path';
import type { Recipe } from '@/types/app';
import { computeRecipeNutritionForSelection } from '@/lib/recipeNutrition';
import { AUTHORED_BREAKFASTS, type AuthoredRecipe } from './recipeSource';

const AUTHORED: AuthoredRecipe[] = [...AUTHORED_BREAKFASTS];

const recipes: Recipe[] = [];
let allVerified = true;

for (const authored of AUTHORED) {
  const result = computeRecipeNutritionForSelection(authored, undefined);
  if (result.confidence !== 'verified') {
    allVerified = false;
    console.error('NOT VERIFIED: ' + authored.id);
    for (const d of result.diagnostics) {
      if (d.via !== 'foodRef' || d.grams == null) console.error('  ' + d.name + ' [' + d.via + ', ' + (d.grams ?? 'no grams') + ']');
    }
  }
  recipes.push({ ...authored, nutritionPerServing: result.nutrition, nutritionConfidence: result.confidence });
  const n = result.nutrition;
  console.log(authored.id.padEnd(30) + String(n.calories).padStart(5) + ' kcal  ' + result.confidence);
}

if (!allVerified) {
  console.error('\nAborting: some recipes are not verified.');
  process.exit(1);
}

const header =
  '// AUTO-GENERATED by scripts/generateRecipes.ts — do not edit by hand.\n' +
  '// Nutrition is computed deterministically from ingredient grams + foodRef.\n' +
  "import { Recipe } from '@/types/app';\n\n" +
  'export const VERIFIED_RECIPE_LIBRARY: Recipe[] = ';
const body = JSON.stringify(recipes, null, 2);
const output = header + body + ';\n';

const projectRoot = path.resolve(__dirname, '..', '..');
const outPath = path.join(projectRoot, 'src', 'lib', 'generated', 'verifiedRecipeCatalog.ts');
fs.writeFileSync(outPath, output, 'utf8');
console.log('\nWrote ' + recipes.length + ' recipes -> ' + path.relative(projectRoot, outPath));
